# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39bfa14c121af97abf3c928862aaddf150c643c1ded1081edf55c4b3731eb4115948042ba11b648f7723f5995374a3c7536969009abb0df9447937ba23c673a3

test:
  secret_key_base: 44bfb839317325bb816575697caa29be24800ae4759587ec3b81b42e51bb3e7479e3983a77bed969c952fb0e20fcfb6b5c2d0e9f9845bf17654b8725d1aa695d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
